Ubuntu-amd64-18.04:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-ubuntu-amd64:18.04
  when: manual

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

Ubuntu-amd64-22.04:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-ubuntu-amd64:22.04
  when: manual

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

CentOS-7-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-centos-amd64:latest
  when: manual
  
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256

almalinux-8-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-almalinux-amd64:8
  when: manual
  
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256

almalinux-8-arm64v8:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-almalinux-arm64v8:8
  when: manual
  
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256

almalinux-9-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-almalinux-amd64:9
  when: manual
  
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256
