Ubuntu-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-ubuntu-amd64:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

Ubuntu-i386:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-ubuntu-i386:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

CentOS-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-centos-amd64:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256

CentOS-i386:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-centos-i386:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256
