Ubuntu-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-ubuntu:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

Ubuntu-i386:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-ubuntu:latest
  when: manual

  script:
    - cmake -DVANILLAPDF_FORCE_32_BIT=ON .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

CentOS-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-centos:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256

CentOS-i386:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-centos:latest
  when: manual

  script:
    - cmake -DVANILLAPDF_FORCE_32_BIT=ON .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256
