Debian:
  image: debian
  when: manual

  before_script:
  - apt-get update --yes
  - apt-get update
  - apt-get install --yes lsb-release g++ dpkg-dev
  - apt-get install --yes cmake zlib1g-dev libssl-dev libjpeg62-turbo-dev

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.sha256

CentOS-amd64:
  image: registry.gitlab.com/jurzik/vanillapdf/vanillapdf-centos:latest
  when: manual

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256

CentOS-i386:
  image: i386/centos
  when: manual
  
  before_script:
  - yum update --yes
  - yum update
  - yum install --yes redhat-lsb-core rpm-build gcc-c++
  - yum install --yes cmake zlib-devel openssl-devel libjpeg-turbo-devel

  script:
    - cmake .
    - make
    - make test
    - make package
  artifacts:
    paths:
      - ./*.rpm
      - ./*.tar.gz
      - ./*.sha256
