#include "unittest.h"

static const char UNIT_TEST_LICENSE[] = R"({
  "version": "1.0",
  "data": {
    "owner": "Vanilla.PDF Labs",
    "note": "Used for running automated test cases",
    "serial": "01E645D2-7158-4DD4-8BA7-8611EBAED44B",
    "updates_expiration": "2028-04-23"
  },
  "signature": "pg4YtQpytS44ZkHj882RCuoWebvHp7cjhRvTQRbMJQ05Ya0wlfxHlmBmXV0PlonlC4ZHFXAoukl51+ZuvetNyLQb7iTWgdzk99bdo646qIdlrFDK4lr2j4PMcXyOqFZQGImKBSASWxIJ97g400spd5rjfMqzoPxM+2RXtl3iHpk2PzfZv07Hnsu3LB8M2fVtENTDrecBjKoTYsWy7Md/TIh0uF3oOD5Zj1TTOVtNAmhwk4Xf8HXah8ymRS4cHB24z/3Luk7NkuTWJ2I8sQ5bM7LGphVVgzEFHZb0kuKn21h1r3BEY13QcHzVizyZ4AsPAK8KFM8KSMAUAShD5ASUOQ==",
  "certificates": [
    "-----BEGIN CERTIFICATE-----\r\nMIIC+zCCAeOgAwIBAgIBAzANBgkqhkiG9w0BAQ0FADAiMSAwHgYDVQQDExdWYW5pbGxhLlBERiBM\r\nYWJzIG1hc3RlcjAeFw0xODA0MTEyMTQxMDBaFw0yODA0MTEyMTQxMDBaMCIxIDAeBgNVBAMTF1Zh\r\nbmlsbGEuUERGIExhYnMgc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Zft\r\n8g+gzDsfN3tS+uL7PJqQCDV7XN10TVTWtQQVb8lFyAeJxsCIui6PqjZBfPNETgL4N2EhFjhoEM17\r\nsQJ/ccGYO5sXAV0UysDEIe4PZf1B7pNOpDcGaMbknY9vyFv/wofD7U7qsJxlffVJHqKRRv2w/06/\r\nFkGwLJsc2yyxHin1LzhlvKbRudUNb079htFN0A3OCvLoLI3pg4jUijLVXCp66pe10C5GE1oFf7OU\r\nGcuLQ9a5EllZvSDSw/I7VCpId7nAsnJvZVphVr2e3tYTGS+4IsjaDUrGU+fscXeliXGKNkVE8DB6\r\nZXKkjIitzuoVAnl/jnmrl93rlo3Y581MsQIDAQABozwwOjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW\r\nBBQMyPgT0z8wbLYClZkM/NkzXd3OKDALBgNVHQ8EBAMCBLAwDQYJKoZIhvcNAQENBQADggEBAKGn\r\ndy4Ug0pLThHUvk9XYE54fOb7nNBEo/O6AAMxU7lQxuN3KLt57iXShOfZQgXCsD0HuAv2iQlKe69X\r\nfS++FuSXZGP/TDRLTr20zer/q3Pi+jcaDQq0XhNqdVmxdbzDhKaXFKFHVSZUU2S1+N2Nbbmf9zyt\r\nO5VlM6WG6UMzMCAGth+7deLGWlRGd4Q9k5s+ddHxYnLcs+9LDCmE5BjVqWng17vuFL2gNIU2l++h\r\nCyS1YKGwS0JXx5wtORWO39LBImrTBkSFke2dGTj1zi7Qng8VDRyX5ewd8nVmhY/DOuQYRTUtS2yd\r\nqBWE/gpbrvxZOzeJ2PAm/S14fqUO/L7Gygk=\r\n-----END CERTIFICATE-----\r\n",
    "-----BEGIN CERTIFICATE-----\r\nMIIDEzCCAfugAwIBAgIBATANBgkqhkiG9w0BAQ0FADAiMSAwHgYDVQQDExdWYW5pbGxhLlBERiBM\r\nYWJzIG1hc3RlcjAgFw0xODA0MTEyMTI5MDBaGA8yMTE4MDQxMTIxMjkwMFowIjEgMB4GA1UEAxMX\r\nVmFuaWxsYS5QREYgTGFicyBtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8\r\n9467IYqcH1omPml0GcQr4KWfTH88885g/+TiJBTc5K3LpZyqpm18stIltqrnFOxiHAALG5j4+0/0\r\n9qs+1N3Q4xoCykyAv1YbtrXaPTS/kx2RE7SsdtLVh0AzpJTxTmcz0zQ0ebubFEPI4JuGdayYf/Zg\r\npfy+x5iKmMypRw2gtZooA6Ffzb6CIBxWxkRgRY0RSXaJVBP3xRt0i6MHWrXZ1A0DnY6HzIRUgH4h\r\nNk/Cpstthj4AAGZq0hTxd16MNIstOt55n2ljSX5PSrh5j4RlwdwBcBbBW5S+sMVWYOBBkjfxYY0c\r\nzdiFqLe7g0NtOCeQdkfNhwVALrG9Gd+0R3/FAgMBAAGjUjBQMA8GA1UdEwEB/wQFMAMBAf8wHQYD\r\nVR0OBBYEFNklCDo8+0G8TL7MH06KyPkxrMWRMAsGA1UdDwQEAwIBBjARBglghkgBhvhCAQEEBAMC\r\nAAcwDQYJKoZIhvcNAQENBQADggEBALVvk/7OvFXNoRekMxg+THcvNcxEtclGPAXms0jj/J0ESH6+\r\ndBu78nUBpRs2QBdormWIGJVwZ4BAzlVvAe0leQquGo4I4xeLr7y9UV3m85a8jAOfgwSJnATmFIwL\r\nv11ScvqKn/+uN16c+U/OBw+wX4AjBzGYsECD83xdmq10AGqd+vYCOI3Ku2KEMLkQnwALkT188Q4/\r\nBQwRbFn4+aZVHyf8tYY+YvtPZ/nb9uoxS5lVKEOTg5VjW4qlS4ZaTinPuxNXRGc1oV6+OO92R6BY\r\n0JPEkWRRMbJvYsxWH/JdGIaySmS41FKnqEaO0QssBKjVg6B0kKPUNG0YApkdFPQBDLY=\r\n-----END CERTIFICATE-----\r\n"
  ]
})";

TestEnvironment::~TestEnvironment() {

}

void TestEnvironment::SetUp() {

    BufferHandle* license_buffer = nullptr;
    boolean_type is_valid = VANILLAPDF_RV_FALSE;
    
    ASSERT_EQ(Buffer_CreateFromData(UNIT_TEST_LICENSE, sizeof(UNIT_TEST_LICENSE), &license_buffer), VANILLAPDF_ERROR_SUCCESS);
    ASSERT_NE(license_buffer, nullptr);

    ASSERT_EQ(LicenseInfo_SetLicenseBuffer(license_buffer), VANILLAPDF_ERROR_SUCCESS);
    ASSERT_EQ(LicenseInfo_IsValid(&is_valid), VANILLAPDF_ERROR_SUCCESS);
    ASSERT_EQ(is_valid, VANILLAPDF_RV_TRUE);
    
    ASSERT_EQ(Buffer_Release(license_buffer), VANILLAPDF_ERROR_SUCCESS);
}

void TestEnvironment::TearDown() {
    ASSERT_EQ(Logging_Shutdown(), VANILLAPDF_ERROR_SUCCESS);
}
