blank_issues_enabled: false
contact_links:
  - name: 📫 General Contact / Support
    url: https://vanillapdf.com/contact/
    about: Use this link for general questions, support, or commercial inquiries.