option(VANILLAPDF_ENABLE_FUZZING "Enable libFuzzer-based fuzz testing (requires Clang)" OFF)

function(enable_fuzzer_for_target target)
    if(VANILLAPDF_ENABLE_FUZZING)
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            message(STATUS "Fuzzer enabled for target: ${target}")
            target_compile_options(${target} PRIVATE -fsanitize=fuzzer,address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=fuzzer,address)
        else()
            message(WARNING "Fuzzer instrumentation requires Clang (found ${CMAKE_CXX_COMPILER_ID})")
        endif()
    endif()
endfunction()

function(enable_fuzzer_coverage_for_target target)
    if(VANILLAPDF_ENABLE_FUZZING)
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            message(STATUS "Fuzzer coverage instrumentation enabled for target: ${target}")
            target_compile_options(${target} PRIVATE -fsanitize=fuzzer-no-link,address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(WARNING "Fuzzer coverage instrumentation requires Clang (found ${CMAKE_CXX_COMPILER_ID})")
        endif()
    endif()
endfunction()
