# GenerateTestCertificates.cmake
# Generates a C++ header file containing test certificates as byte arrays
#
# Usage:
#   generate_test_certificates_header(
#       OUTPUT_FILE <output_header_path>
#       CERTIFICATES_DIR <directory_containing_pfx_files>
#   )

function(generate_test_certificates_header)
    cmake_parse_arguments(GEN "" "OUTPUT_FILE;CERTIFICATES_DIR" "" ${ARGN})

    if(NOT GEN_OUTPUT_FILE)
        message(FATAL_ERROR "OUTPUT_FILE is required")
    endif()

    if(NOT GEN_CERTIFICATES_DIR)
        message(FATAL_ERROR "CERTIFICATES_DIR is required")
    endif()

    # Find all PFX files in the certificates directory
    file(GLOB CERTIFICATE_FILES "${GEN_CERTIFICATES_DIR}/*.pfx")

    # Start building the header content
    set(HEADER_CONTENT "// Auto-generated file - DO NOT EDIT\n")
    string(APPEND HEADER_CONTENT "// Generated by CMake from the unittest certificates/*.pfx fixtures\n")
    string(APPEND HEADER_CONTENT "// Regenerate by reconfiguring CMake\n\n")
    string(APPEND HEADER_CONTENT "#ifndef _VANILLAPDF_TEST_CERTIFICATES_H\n")
    string(APPEND HEADER_CONTENT "#define _VANILLAPDF_TEST_CERTIFICATES_H\n\n")
    string(APPEND HEADER_CONTENT "#include <cstdint>\n")
    string(APPEND HEADER_CONTENT "#include <cstddef>\n\n")

    foreach(CERT_FILE ${CERTIFICATE_FILES})
        # Get the filename without path and extension
        get_filename_component(CERT_NAME ${CERT_FILE} NAME_WE)

        # Convert filename to valid C identifier (replace - with _)
        string(REPLACE "-" "_" CERT_VAR_NAME ${CERT_NAME})
        string(TOUPPER ${CERT_VAR_NAME} CERT_VAR_NAME_UPPER)

        # Read the file as hex
        file(READ ${CERT_FILE} CERT_HEX HEX)

        # Get file size
        file(SIZE ${CERT_FILE} CERT_SIZE)

        # Convert hex string to comma-separated bytes
        string(LENGTH "${CERT_HEX}" HEX_LENGTH)
        set(BYTE_ARRAY "")
        set(BYTES_PER_LINE 16)
        set(BYTE_COUNT 0)

        math(EXPR NUM_BYTES "${HEX_LENGTH} / 2")

        foreach(BYTE_IDX RANGE 0 ${NUM_BYTES})
            if(BYTE_IDX EQUAL NUM_BYTES)
                break()
            endif()

            math(EXPR HEX_POS "${BYTE_IDX} * 2")
            string(SUBSTRING "${CERT_HEX}" ${HEX_POS} 2 BYTE_HEX)

            if(BYTE_COUNT GREATER 0)
                string(APPEND BYTE_ARRAY ", ")
            endif()

            # Add newline and indentation every BYTES_PER_LINE bytes
            math(EXPR MOD_RESULT "${BYTE_COUNT} % ${BYTES_PER_LINE}")
            if(MOD_RESULT EQUAL 0 AND BYTE_COUNT GREATER 0)
                string(APPEND BYTE_ARRAY "\n    ")
            endif()

            string(APPEND BYTE_ARRAY "0x${BYTE_HEX}")
            math(EXPR BYTE_COUNT "${BYTE_COUNT} + 1")
        endforeach()

        # Add comment with certificate info
        string(APPEND HEADER_CONTENT "// Certificate: ${CERT_NAME}.pfx (${CERT_SIZE} bytes)\n")
        string(APPEND HEADER_CONTENT "// Password: \"test\" (standard test password)\n")
        string(APPEND HEADER_CONTENT "static const unsigned char ${CERT_VAR_NAME_UPPER}_CERTIFICATE[] = {\n")
        string(APPEND HEADER_CONTENT "    ${BYTE_ARRAY}\n")
        string(APPEND HEADER_CONTENT "};\n")
        string(APPEND HEADER_CONTENT "static const size_t ${CERT_VAR_NAME_UPPER}_CERTIFICATE_SIZE = sizeof(${CERT_VAR_NAME_UPPER}_CERTIFICATE);\n\n")

        message(STATUS "Generated certificate data: ${CERT_VAR_NAME_UPPER}_CERTIFICATE (${CERT_SIZE} bytes)")
    endforeach()

    string(APPEND HEADER_CONTENT "#endif /* _VANILLAPDF_TEST_CERTIFICATES_H */\n")

    # Write the header file
    file(WRITE ${GEN_OUTPUT_FILE} "${HEADER_CONTENT}")
    message(STATUS "Generated test certificates header: ${GEN_OUTPUT_FILE}")
endfunction()
