option(VANILLAPDF_ENABLE_STACK_SANITIZER "Enable stack sanitizer instrumentation (use with Debug builds)" OFF)

include(CheckCXXCompilerFlag)

function(enable_stack_sanitizer_for_target target)
    if(VANILLAPDF_ENABLE_STACK_SANITIZER)
        if(MSVC)
            message(STATUS "Stack sanitizer enabled for target: ${target}")
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /fsanitize=address)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
            check_cxx_compiler_flag("-fsanitize=address" SANITIZER_SUPPORTED)
            find_library(ASAN_LIBRARY NAMES asan)
            if(SANITIZER_SUPPORTED AND ASAN_LIBRARY)
                message(STATUS "Stack sanitizer enabled for target: ${target}")
                target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
                target_link_options(${target} PRIVATE -fsanitize=address)
            else()
                message(WARNING "Stack sanitizer requested but not available on this platform")
            endif()
        else()
            message(WARNING "Stack sanitizer is not supported for this compiler")
        endif()
    endif()
endfunction()
