option(VANILLAPDF_ENABLE_STACK_SANITIZER "Enable address sanitizer instrumentation (use with Debug builds)" OFF)
option(VANILLAPDF_ENABLE_THREAD_SANITIZER "Enable thread sanitizer instrumentation (use with Debug builds)" OFF)
option(VANILLAPDF_ENABLE_UB_SANITIZER "Enable undefined behavior sanitizer instrumentation (use with Debug builds)" OFF)

function(enable_stack_sanitizer_for_target target)
    if(VANILLAPDF_ENABLE_STACK_SANITIZER)
        if(MSVC)
            message(STATUS "Address sanitizer enabled for target: ${target}")
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /fsanitize=address)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
            message(STATUS "Address sanitizer enabled for target: ${target}")
            target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(WARNING "Address sanitizer is not supported for this compiler")
        endif()
    endif()
    
    if(VANILLAPDF_ENABLE_THREAD_SANITIZER)
        if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
            message(STATUS "Thread sanitizer enabled for target: ${target}")
            target_compile_options(${target} PRIVATE -fsanitize=thread)
            target_link_options(${target} PRIVATE -fsanitize=thread)
        else()
            message(WARNING "Thread sanitizer is not supported for this compiler")
        endif()
    endif()
    
    if(VANILLAPDF_ENABLE_UB_SANITIZER)
        if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
            message(STATUS "Undefined behavior sanitizer enabled for target: ${target}")
            target_compile_options(${target} PRIVATE -fsanitize=undefined)
            target_link_options(${target} PRIVATE -fsanitize=undefined)
        else()
            message(WARNING "Undefined behavior sanitizer is not supported for this compiler")
        endif()
    endif()
endfunction()
