# Prevent POSIX thread detection on MSVC static builds
if (MSVC AND NOT BUILD_SHARED_LIBS)
  set(CMAKE_THREAD_PREFER_PTHREAD OFF CACHE BOOL "" FORCE)
  set(THREADS_PREFER_PTHREAD_FLAG OFF CACHE BOOL "" FORCE)
endif()