/* Define pricing constants */

var PERSONAL_LICENSE_PRICE				= {{ PERSONAL_LICENSE_PRICE }};
var PERSONAL_ONE_YEAR_SUPPORT_PRICE		= {{ PERSONAL_ONE_YEAR_SUPPORT_PRICE }};
var PERSONAL_TWO_YEAR_SUPPORT_PRICE		= {{ PERSONAL_TWO_YEAR_SUPPORT_PRICE }};
var PERSONAL_THREE_YEAR_SUPPORT_PRICE	= {{ PERSONAL_THREE_YEAR_SUPPORT_PRICE }};

var COMMERCIAL_LICENSE_PRICE			= {{ COMMERCIAL_LICENSE_PRICE }};
var COMMERCIAL_ONE_YEAR_SUPPORT_PRICE	= {{ COMMERCIAL_ONE_YEAR_SUPPORT_PRICE }};
var COMMERCIAL_TWO_YEAR_SUPPORT_PRICE	= {{ COMMERCIAL_TWO_YEAR_SUPPORT_PRICE }};
var COMMERCIAL_THREE_YEAR_SUPPORT_PRICE	= {{ COMMERCIAL_THREE_YEAR_SUPPORT_PRICE }};
