name: Build Homebrew package

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'release/*'
    paths:
      - .github/workflows/build-brew-package.yml

  pull_request:
    branches:
      - main
      - 'release/*'
    paths:
      - .github/workflows/build-brew-package.yml

  schedule:
    - cron: '0 3 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-package:
    name: Build package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install system dependencies
        run: |
          brew update
          brew install ninja openssl@3 jpeg-turbo zlib openjpeg spdlog nlohmann-json googletest

      - name: Configure
        run: |
          cmake --preset macos-arm64 -DCMAKE_BUILD_TYPE=Release \
            -DVANILLAPDF_INTERNAL_VCPKG=OFF \
            -DVANILLAPDF_ENABLE_PACKAGING=ON \
            -DVANILLAPDF_ENABLE_TESTS=ON \
            -DVANILLAPDF_ENABLE_ENCRYPTION=ON -DVANILLAPDF_EXTERNAL_OPENSSL=ON \
            -DVANILLAPDF_ENABLE_JPEG=ON -DVANILLAPDF_EXTERNAL_JPEG=ON \
            -DVANILLAPDF_ENABLE_JPEG2000=ON -DVANILLAPDF_EXTERNAL_OPENJPEG=ON \
            -DVANILLAPDF_ENABLE_ZLIB=ON -DVANILLAPDF_EXTERNAL_ZLIB=ON \
            -DVANILLAPDF_EXTERNAL_SPDLOG=ON \
            -DVANILLAPDF_EXTERNAL_NLOHMANN_JSON=ON \
            -DVANILLAPDF_EXTERNAL_GTEST=ON

      - name: Build
        run: cmake --build --preset macos-arm64

      - name: Test
        run: ctest --preset macos-arm64

      - name: Package
        run: cmake --build --preset macos-arm64 --target package

      - name: Upload DMG
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6
        with:
          name: vanillapdf-dmg
          path: build/macos-arm64/*.dmg
