# This is a basic workflow to help you get started with Actions

name: Build OS X

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
          brew install openssl@3
      
      - name: Update library paths
        run: |
          export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

      # Runs a single command using the runners shell
      - name: Generate CMake project
        run: cmake . -DPLATFORM_IDENTIFIER=osx.12-x64
      
      - name: Build project
        run: make
      
      - name: Run automated test scenarios
        run: make test
      
      - name: Build installer packages
        run: make package
        
      - name: Upload result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: install-package
          path: |
            ./*.zip
            ./*.dmg
