# This is a basic workflow to help you get started with Actions

name: Build OS X

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
          brew update
          brew install cmake
          brew install python@3
          brew install jpeg
          brew install zlib
      
      - name: Update library paths
        run: |
          export LDFLAGS="-L/usr/local/opt/libressl/lib"
          export CPPFLAGS="-I/usr/local/opt/libressl/include"
          export OPENSSL_ROOT_DIR=/usr/local/opt/libressl

      # Runs a single command using the runners shell
      - name: Generate CMake project
        run: cmake . -DPLATFORM_IDENTIFIER=osx.12-x64 -DOPENSSL_ROOT_DIR=/usr/local/opt/libressl
      
      - name: Build project
        run: make
      
      - name: Run automated test scenarios
        run: make test
      
      - name: Build installer packages
        run: make package
