name: Build Debian package

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'release/*'
    paths:
      - .github/workflows/build-deb-package.yml

  pull_request:
    branches:
      - main
      - 'release/*'
    paths:
      - .github/workflows/build-deb-package.yml

  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: read

jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libjpeg-turbo8 libjpeg-turbo8-dev zlib1g-dev

      - name: Configure
        run: |
          cmake --preset linux-x64-gcc -DCMAKE_BUILD_TYPE=Release \
            -DVANILLAPDF_STANDALONE=ON \
            -DVANILLAPDF_EXTERNAL_OPENSSL=ON \
            -DVANILLAPDF_EXTERNAL_JPEG=ON \
            -DVANILLAPDF_EXTERNAL_OPENJPEG=OFF \
            -DVANILLAPDF_EXTERNAL_ZLIB=ON \
            -DVANILLAPDF_EXTERNAL_SPDLOG=OFF \
            -DVANILLAPDF_EXTERNAL_NLOHMANN_JSON=OFF \
            -DDETECT_CUSTOM_LINUX_DISTRIBUTION=ON \
            -DVANILLAPDF_ENABLE_TESTS=ON -DVANILLAPDF_EXTERNAL_GTEST=OFF \
            -DVANILLAPDF_ENABLE_BENCHMARK=ON -DVANILLAPDF_EXTERNAL_BENCHMARK=OFF

      - name: Build
        run: cmake --build --preset linux-x64-gcc

      - name: Test
        run: ctest --preset linux-x64-gcc

      - name: Package
        run: cmake --build --preset linux-x64-gcc --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vanillapdf-deb
          path: build/linux-x64-gcc/*.deb
