# This is a basic workflow to help you get started with Actions

name: Nightly full scan

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run workflow on any push into main branch
  # only there was a change in the workflow file
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/nightly-check.yml'

  # Run workflow when there is a pull request towards main branch
  # only there was a change in the workflow file
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/nightly-check.yml'

  schedule:
    - cron: '0 2 * * 1'  # Every on Monday at 2 AM UTC

# Enable only minimum required permissions
permissions:
  contents: read    # Download the repository source code
  packages: read    # Needed to load container images

env:
  VCPKG_ROOT: external/vcpkg
  VCPKG_DISABLE_METRICS: 1 # vcpkg is by default sending build metrics, we do not need it here
  VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/external/vcpkg/bincache,readwrite"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  linux:
    name: ${{ matrix.config.name }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        build_type: [Debug, Release]

        config:
          - name: ubuntu.22.04-x64
            os: ubuntu-24.04
            image: ghcr.io/vanillapdf/vanillapdf-ubuntu-amd64:22.04
            platform: linux/amd64
            preset: linux-x64-gcc

          # TODO:
          # Ubuntu 22.04 arm image cannot be built on windows due to QEMU bug
          # - name: ubuntu.22.04-arm64
          #   os: ubuntu-24.04-arm
          #   image: ghcr.io/vanillapdf/vanillapdf-ubuntu-arm64v8:22.04
          #   platform: linux/arm64
          #   preset: linux-arm64-gcc

          - name: ubuntu.24.04-x64
            os: ubuntu-24.04
            image: ghcr.io/vanillapdf/vanillapdf-ubuntu-amd64:24.04
            platform: linux/amd64
            preset: linux-x64-gcc

          - name: ubuntu.24.04-arm64
            os: ubuntu-24.04-arm
            image: ghcr.io/vanillapdf/vanillapdf-ubuntu-arm64v8:24.04
            platform: linux/arm64
            preset: linux-arm64-gcc

          - name: rocky.8-x64
            os: ubuntu-24.04
            image: ghcr.io/vanillapdf/vanillapdf-rockylinux-amd64:8
            platform: linux/amd64
            preset: linux-x64-gcc

          - name: rocky.8-arm64
            os: ubuntu-24.04-arm
            image: ghcr.io/vanillapdf/vanillapdf-rockylinux-arm64v8:8
            platform: linux/arm64
            preset: linux-arm64-gcc

          - name: rocky.9-x64
            os: ubuntu-24.04
            image: ghcr.io/vanillapdf/vanillapdf-rockylinux-amd64:9
            platform: linux/amd64
            preset: linux-x64-gcc

          - name: rocky.9-arm64
            os: ubuntu-24.04-arm
            image: ghcr.io/vanillapdf/vanillapdf-rockylinux-arm64v8:9
            platform: linux/arm64
            preset: linux-arm64-gcc

    container:
      image: ${{ matrix.config.image }}
      options: --platform=${{ matrix.config.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            build/${{ matrix.config.preset }}/vcpkg_installed
            external/vcpkg/downloads
            external/vcpkg/bincache
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json', 'cmake/overlays/*.cmake') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      - name: Bootstrap vcpkg (Linux)
        run: ./external/vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Configure ${{ matrix.config.preset }}
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.config.preset }}
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: Test ${{ matrix.config.preset }}
        run: ctest --preset ${{ matrix.config.preset }} --output-on-failure


  windows:
    name: ${{ matrix.config.name }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:

        # There are some issues with win-x86 in debug, that prevent us to use it
        build_type: [Release]

        config:
          - { name: "win.2022-x86", os: windows-2022, preset: "windows-x86-msvc-17" }
          - { name: "win.2025-x86", os: windows-2025, preset: "windows-x86-msvc-17" }
          - { name: "win.2022-x64", os: windows-2022, preset: "windows-x64-msvc-17" }
          - { name: "win.2025-x64", os: windows-2025, preset: "windows-x64-msvc-17" }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            build/${{ matrix.config.preset }}/vcpkg_installed
            external/vcpkg/downloads
            external/vcpkg/bincache
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json', 'cmake/overlays/*.cmake') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      - name: Bootstrap vcpkg (Windows)
        run: ${{ github.workspace }}\\external\\vcpkg\\bootstrap-vcpkg.bat

      - name: Configure ${{ matrix.config.preset }}
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.config.preset }}
        run: cmake --build --preset ${{ matrix.config.preset }} --config ${{ matrix.build_type }}

      - name: Test ${{ matrix.config.preset }}
        run: ctest --preset ${{ matrix.config.preset }} -C ${{ matrix.build_type }} --output-on-failure


  macos:
    name: ${{ matrix.config.name }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.runner }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

        config:
          - { name: "osx.13-x64", runner: macos-13, preset: "macos-x64" }
          - { name: "osx.14-arm64", runner: macos-14, preset: "macos-arm64" }
          - { name: "osx.15-arm64", runner: macos-15, preset: "macos-arm64" }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            build/${{ matrix.config.preset }}/vcpkg_installed
            external/vcpkg/downloads
            external/vcpkg/bincache
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json', 'cmake/overlays/*.cmake') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      - name: Install build tools (macOS)
        run: brew install --quiet autoconf automake autoconf-archive

      - name: Bootstrap vcpkg (macOS)
        run: ${{ github.workspace }}/external/vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Configure
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.config.preset }} --output-on-failure

