name: Nightly NuGet Packages

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC

  workflow_dispatch:

permissions:
  contents: write  # Needed for future GitHub release or content access
  packages: read   # Needed to load container images

env:
  VCPKG_DISABLE_METRICS: 1
  VCPKG_ROOT: external/vcpkg

jobs:
  build-runtimes:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "win.2025-x86", os: windows-2025,   preset: "windows-x86-msvc", configuration: Release }
          - { name: "win.2025-x64", os: windows-2025,   preset: "windows-x64-msvc", configuration: Release }
          - { name: "osx.13-x64", os: macos-13,         preset: "macos-x64",        configuration: Release }
          - { name: "osx.15-arm64", os: macos-15,       preset: "macos-arm64",      configuration: Release }
          - { name: "rocky.9-x64", os: ubuntu-latest,   preset: "linux-x64-gcc",    configuration: Release, container: 'ghcr.io/vanillapdf/vanillapdf-rockylinux-amd64:9' }
          - { name: "rocky.9-arm64", os: ubuntu-latest, preset: "linux-arm64-gcc",  configuration: Release, container: 'ghcr.io/vanillapdf/vanillapdf-rockylinux-arm64v8:9' }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: |
            build/vcpkg_installed
            external/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y mono-complete

      # Cross-platform vcpkg bootstrap handling
      - name: Bootstrap vcpkg
        uses: ./.github/actions/bootstrap-vcpkg

      # Cross-platform vcpkg bootstrap handling
      - name: Set nightly version suffix
        run: echo "DATE_SUFFIX=-nightly-$(date +'%Y%m%d')" >> $GITHUB_ENV

      # Configure CMake project
      - name: Configure CMake for ${{ matrix.config.preset }}
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.config.configuration }} -DVANILLAPDF_VERSION_BUILD_SUFFIX=${{ env.DATE_SUFFIX }}
        
      - name: Build using ${{ matrix.config.preset }}
        run: cmake --build --preset ${{ matrix.config.preset }} --config ${{ matrix.config.configuration }}

      - name: Test using ${{ matrix.config.preset }}
        run: ctest --preset ${{ matrix.config.preset }} --config ${{ matrix.config.configuration }}

      - name: Build NuGet package
        run: nuget pack nuget/vanillapdf.runtime.nuspec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vanillapdf-runtime-nightly-nuget-${{ matrix.config.preset }}-${{ env.DATE_SUFFIX }}
          path: |
            *.nupkg

  build-vanillapdf-core:
    name: vanillapdf core
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false

      matrix:
        config:
          - { name: "win.2025-x64", os: windows-2025, preset: "windows-x64-msvc" }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: |
            build/vcpkg_installed
            external/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      - name: Set nightly version suffix
        run: echo "DATE_SUFFIX=-nightly-$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Configure CMake for ${{ matrix.config.preset }}
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.config.configuration }} -DVANILLAPDF_VERSION_BUILD_SUFFIX=${{ env.DATE_SUFFIX }}

      - name: Build NuGet package
        run: nuget pack nuget/vanillapdf.nuspec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vanillapdf-nightly-nuget-${{ env.DATE_SUFFIX }}
          path: |
            *.nupkg
