# This is a basic workflow to help you get started with Actions

name: Sanity check

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

permissions:
  contents: read    # Download the repository source code
  packages: read    # Needed to load container images

env:
  VCPKG_ROOT: external/vcpkg
  VCPKG_DISABLE_METRICS: 1 # vcpkg is by default sending build metrics, we do not need it here

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  linux:
    name: Build on Linux (${{ matrix.config.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # We would like to see the results of all jobs even in case one of them fails
      matrix:
        config:
          - name: rocky.9-x64
            image: ghcr.io/vanillapdf/vanillapdf-rockylinux-amd64:9
            platform: linux/amd64
            preset: linux-x64-gcc
            configuration: Release

          - name: rocky.9-arm64
            image: ghcr.io/vanillapdf/vanillapdf-rockylinux-arm64v8:9
            platform: linux/arm64
            preset: linux-arm64-gcc
            configuration: Release

          - name: ubuntu.24.04-x64
            image: ghcr.io/vanillapdf/vanillapdf-ubuntu-amd64:24.04
            platform: linux/amd64
            preset: linux-x64-gcc
            configuration: Release

          - name: ubuntu.24.04-arm64
            image: ghcr.io/vanillapdf/vanillapdf-ubuntu-arm64v8:24.04
            platform: linux/arm64
            preset: linux-arm64-gcc
            configuration: Release

    container:
      image: ${{ matrix.config.image }}
      options: --platform=${{ matrix.config.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: |
            build/vcpkg_installed
            external/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      # Bootstrap vcpkg on Linux
      - name: Bootstrap vcpkg (Linux)
        run: ./external/vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Generate build files
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.config.configuration }}

      - name: Build
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.config.preset }} --output-on-failure


  windows:
    name: Build on Windows
    runs-on: windows-2025
    strategy:
      fail-fast: false # We would like to see the results of all jobs even in case one of them fails

      matrix:
        config:
          - name: win.2025-x86
            preset: windows-x86-msvc-17
            configuration: Release

          - name: win.2025-x64
            preset: windows-x64-msvc-17
            configuration: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: |
            build/vcpkg_installed
            external/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      # Bootstrap vcpkg on Windows
      - name: Bootstrap vcpkg (Windows)
        run: ${{ github.workspace }}\\external\\vcpkg\\bootstrap-vcpkg.bat
        shell: cmd

      - name: Generate build files ${{ matrix.config.preset }}
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.config.configuration }}

      - name: Build ${{ matrix.config.preset }}
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: Test ${{ matrix.config.preset }}
        run: ctest --preset ${{ matrix.config.preset }} --config ${{ matrix.config.configuration }} --output-on-failure

  macos:
    name: Build on macOS
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: false # We would like to see the results of all jobs even in case one of them fails
      matrix:
        config:
          - name: osx.13-x64
            runner: macos-13
            preset: macos-x64
            configuration: Release

          - name: osx.15-arm64
            runner: macos-15
            preset: macos-arm64
            configuration: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: |
            build/vcpkg_installed
            external/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.config.preset }}-
            vcpkg-${{ runner.os }}-

      - name: Install build tools (macOS)
        run: brew install autoconf automake autoconf-archive

      # Bootstrap vcpkg on macOS
      - name: Bootstrap vcpkg (macOS)
        run: ${{ github.workspace }}/external/vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Generate build files
        run: cmake --preset ${{ matrix.config.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.config.configuration }}

      - name: Build
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.config.preset }} --output-on-failure
