name: Validate Workflows

on:
  pull_request:
    branches: [ "main", "release/*" ]
    paths:
      - '.github/workflows/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yaml-lint:
    name: YAML syntax
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Validate YAML syntax
        run: python3 scripts/validate_workflows.py .github/workflows/*.yml
